version: '3'

services:

  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - db_volume:/var/lib/mysql
    restart: always
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wp_volume:/var/www/html
    restart: always
    networks:
      - inception

  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wp_volume:/var/www/html
    restart: always
    networks:
      - inception

volumes:
  db_volume:
    driver: local
    # volumes are created on host machine
    driver_opts:
      type: none
      # no special partition in the host machine
      device: /home/${USER}/data/mariadb
      # location in host machine
      o: bind
      # bind mount sets path outside docker ie. in the host machine
  wp_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress
      o: bind

networks:
  inception:
    # name: inception-network
    driver: bridge
