version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
  db:
    image: "mysql"
    environment:
      MYSQL_ROOT_PWD: mysql_root_rootpwd123
    volumes:
      - db-data:/foo

volumes:
  db-data:
